version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - go-postgres:/data/postgres
      - ./database/postgres/create-database.sql:/docker-entrypoint-initdb.d/create-database.sql
      - ./database/postgres/backup:/backup  # Mapping backup directory
    restart: always
    networks:
      - postgres-network

volumes:
  go-postgres:
networks: 
  postgres-network:
    driver: bridge